### ISSUE TITLE
Unexpected end of JSON errors for optional DataqueryArray types in generated Go code

### ISSUE THREAD

**Issue by andybradshaw** [grafana/cog#328]
### Issue Summary

Generated go code for optional Dataquery (and DataqueryArray) types doesn't perform any checks before attempting to deserialize, which can lead to `panic: unexpected end of JSON input` errors.

[Cue type definition](https://github.com/grafana/kind-registry/blob/6c763e7d2869a024ce499e3b78ec427eacc98824/grafana/next/core/dashboard/dashboard.cue#L540-L541):
```
// Depends on the panel plugin. See the plugin documentation for details.
targets?: [...#Target]
```

[Generated deser code](https://github.com/grafana/grafana-foundation-sdk/blob/8fd713f5bd12d1b1ff16b929c44266dbd1aa699d/go/dashboard/types_json_marshalling_gen.go#L195):
```golang
dataqueryTypeHint := ""
if resource.Datasource != nil && resource.Datasource.Type != nil {
	dataqueryTypeHint = *resource.Datasource.Type
}

targets, err := cog.UnmarshalDataqueryArray(fields["targets"], dataqueryTypeHint)
if err != nil {
	return err
}
resource.Targets = targets
```
### Minimal Issue Reproduction

I've included a minimal(-ish) repro based on some dashboards that we have in production. While trying to create a repro locally, it seems that this is not the default panel json that gets created on the latest text panel version (it includes the `datasource` and `targets` fields), but seems like something that the generated code can be defensive against. 

Dashboard json:
```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 1,
  "links": [],
  "panels": [
    {
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "code": {
          "language": "plaintext",
          "showLineNumbers": false,
          "showMiniMap": false
        },
        "content": "test content",
        "mode": "markdown"
      },
      "pluginVersion": "10.4.2",
      "type": "text"
    }
  ],
  "schemaVersion": 39,
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "browser",
  "title": "repro deser error",
  "uid": "fdk17npdk7ldsa",
  "version": 3,
  "weekStart": ""
}
```

code attempting to read this dashboard (pulled from the [go sdk readme](https://github.com/andybradshaw/grafana-foundation-sdk/tree/next%2Bcog-v0.0.x-preview-1714233429/go#unmarshaling-a-dashboard)):
```
package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/grafana/grafana-foundation-sdk/go/cog/plugins"
	"github.com/grafana/grafana-foundation-sdk/go/dashboard"
)

func main() {
	// Required to correctly unmarshal panels and dataqueries
	plugins.RegisterDefaultPlugins()

	dashboardJSON, err := os.ReadFile("dashboard.json")
	if err != nil {
		panic(err)
	}

	sampleDashboard := &dashboard.Dashboard{}
	if err := json.Unmarshal(dashboardJSON, sampleDashboard); err != nil {
		panic(fmt.Sprintf("%s", err))
	}

	fmt.Printf("%#v\n", sampleDashboard)
}
```

```
$ ./main
panic: unexpected end of JSON input
```

**Comment by K-Phoen** [comment]
Thanks for this great issue report and the PR that followed it, they're both very much appreciated :)

Closing this, since #329 is now merged.
