### ISSUE TITLE
Investigate how to generate schemas from models in code

### ISSUE THREAD

**Issue by K-Phoen** [grafana/cog#71]
Gaining access to a wide range of schemas would become easier if engineers didn't have to manually write these schemas as we currently do with Cue/Thema/Kindsys.

A possible approach would be to generate schemas from models existing in our codebase, for example with tools such as:

* https://github.com/vega/ts-json-schema-generator
* https://github.com/invopop/jsonschema
* https://pkg.go.dev/github.com/getkin/kin-openapi/openapi3gen
* https://github.com/glideapps/quicktype
* ...

Goals:

* identify a tool that could be used to generate schemas from Typescript types
* identify a tool that could be used to generate schemas from Go types
* suggest how an integration with grafana/grafana could look like
* suggest how [metadata](https://github.com/grafana/cog/blob/ac8ba4a104737ac1d99ea824cf8062e48081a217/internal/ast/schema.go#L75-L79) could be added to the generated schemas
* write a design doc

**Comment by Duologic** [comment]
Findings on Typescript->JSON schema:
 - [vega/ts-json-schema-generator](https://github.com/vega/ts-json-schema-generator) doesn't have support for Yarn workspaces, this is used in grafana/grafana to resolve imports
 - [YousefED/typescript-json-schema](https://github.com/YousefED/typescript-json-schema) has yielded better results:
   - it doesn't allow to use `oneOf` discriminators, always defaults to `anyOf`, we can probably workaround this with annotations
   - it doesn't work well with JSX (*.tsx files), just runs forever until it runs out of memory/heap, I probably don't know enough about javascript/typescript to understand this, creating a *.ts file that has the correct interface should be a good workaround
    - the code of the panels often have an interface `Props` that hold the complete data model for that panel, this leads to non-unique names and all that, creating a *.ts file that has a proper interface name should be a good workaround (compounds to above)

**Comment by Duologic** [comment]
I briefly tried [glideapps/quicktype](https://github.com/glideapps/quicktype) but the Typescript->Schema seems very immature, no way to include compilerOptions form tsconfig.json.

I've tried [invopop/jsonschema](https://github.com/invopop/jsonschema) in past projects related to CRDsonnet, it worked great, but I think we could do more with go-swagger that is also used in grafana/grafana.

**Comment by Duologic** [comment]
After more experimentation with [YousefED/typescript-json-schema](https://github.com/YousefED/typescript-json-schema), I've overcome some issues, remaining problems:
- `anyOf` is the only discriminator (see above)
- functions are also exported as properties
  - charaterized by the **on** keyword, like onClick
  - workaround: `@TJS-ignore` annotation
- interfaces with generics are exported with an annoying syntax
  - they look like `DataLink<any>` 
  - some generics are not really that useful to have in the schema anyway (like <any>)

**Comment by K-Phoen** [comment]
https://github.com/vega/ts-json-schema-generator looks like a promising option, probably easier to extend as well for more advanced parsing/formatting behaviors

I could integrate it with grafana/grafana and have it generate schemas (not for every interesting object though since it currently fails for some types).

Worth digging deeper into it and maybe submitting fixes/changes upstream.
